### ISSUE TITLE
Create report from multiple folders

### ISSUE THREAD

**Issue by b82** [eventOneHQ/npm-audit-html#16]
Is it possible to create a report from different folders?
When I have a big project with submodules with theyr dependencies I have to run multiple times npm audit, with the result that I have many html reports. 
I'd like to tell npm audit a way (ex. npm audit --merge ./project/*/package.json - where * is a wildcard for every subfolder to check) to watch every submodules and merge the reports into one.

**Comment by nprail** [comment]
Interesting use case. I can see how that would be super useful, especially with microservices. 

Although, what you're looking for seems to be more like an npm feature. I'm not sure how `npm-audit-html` could support that without actually wrapping npm instead of piping from it.

**Comment by b82** [comment]
Thank you very much @nprail for your quick reply.
So do you think it could be better ask directly to NPM? 
Meanwhile I've found this (https://gist.github.com/aravindkumarsvg/6169b8812b6e96f54737128a6f24fe4c), It's not perfect (it doesn't report errors), maybe it could be helpful to someone

**Comment by nprail** [comment]
@b82 Yeah, either create an issue with either npm or maybe one of the mono-repo helpers like Lerna. Seems like it might be more in the scope of the latter. 

If npm or Lerna do add support for this use case, I'd gladly make any modifications needed for `npm-audit-html` to better support it.
