### ISSUE TITLE
Compatibility with audit-ci

### ISSUE THREAD

**Issue by dhacc** [eventOneHQ/npm-audit-html#21]
Hi, I would like to ask whether npm-audit-html would have compatibility with audit-ci (https://www.npmjs.com/package/audit-ci)?

Since audit-ci has the advantages of e.g. being able to whitelist packages and advisories, set threshold level, and setting those configs in a single config file, what normal npm audit unfortunately does not have. 

Thanks!

**Comment by nprail** [comment]
Interesting, I've never heard of `audit-ci`. It looks like a useful tool. 

Based on my brief glance at the `audit-ci` docs, looks like `npm-audit-html` doesn't support it currently. 

`npm-audit-html` requires a JSON output of the vulnerabilities in the same format that `npm audit --json` uses. 

However, it looks like `audit-ci` has a report-type flag. I wonder if you can specify your own reporter?

**Comment by dhacc** [comment]
Âctually I already wrote a JSON-Extractor to extract only the JSON part of audit-ci's output, and hard-coded the rest of the output to imitate npm audit's output just to see if it works, but it doesn't.

Additionally, I also wrote the output of the normal "npm audit" in a JSON-file, and use it as input for npm-audit-html by using `echo output.json | npm-audit-html`, but it doesn't work either.

Can you suggest some kind of workaround, so that npm-audit-html can take file as input, for example? Thanks!

**Comment by nprail** [comment]
Interesting, I would think that would work. What error message are you getting? 

I'll do some experimenting too.

**Comment by dhacc** [comment]
Thanks for your quick response!

The error says
```
Failed to parse NPM Audit JSON!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
...
```
And here's what I did:
```
npm audit --json > npm-audit-output.json
echo npm-audit-output.json | npm run npm-audit-html
```

Hope it helps and hope you find something useful!

**Comment by nprail** [comment]
Oh, use `cat` instead of `echo`. That should make it work. `echo npm-audit-output.json` will respond with `npm-audit-output.json` instead of the files contents.

**Comment by dhacc** [comment]
It works wonderfully, thanks!!

Here's the regex to parse the audit-ci, in case you or someone else need it:

var regex = /(\{[^]*\})/;
