### ISSUE TITLE
Add support to --input as json file

### ISSUE THREAD

**Issue by faris-git** [eventOneHQ/npm-audit-html#25]
Currently `npm-audit-html` only support `stdin` as input. It would be great if it could accept json file as input. 
Something like this `npm-audit-html --input audit.json --output report.html`.

Also would be nice if it's support threshold(low, moderate, high, critical).

**Comment by nprail** [comment]
Adding an `--input` option makes a lot of sense. Should be easy enough to add too. 

I'm curious as to what your use-case is? 

Threshold filtering is planned (see #2).

**Comment by faris-git** [comment]
> Adding an `--input` option makes a lot of sense. Should be easy enough to add too.
Yes, I'm waiting for it in next version :)

> I'm curious as to what your use-case is?
I've a jenkins pipeline job which publishes NPM report as html for each build. Unfortunately I didn't find any package having support for all those options (audit thresholds + html as output). Now I need to use 2 package to make a html report and each npm package runs `npm audit`, that means 2x times executed which is superfluous and time consuming.  The first package supports thresholds and can output only as json(but won't support html). So I need to use npm-audit-html for HTML.

> Threshold filtering is planned (see #2).
That would be great

Thanks for this nice npm package
