### ISSUE TITLE
Add option to open generated report

### ISSUE THREAD

**Issue by nikolay-borzov** [eventOneHQ/npm-audit-html#45]
Similar to what `webpack-bundle-analyzer` does.
`open` package can be used to open a generated report.

**Comment by nprail** [comment]
It looks like `webpack-bundle-analyzer` actually creates a little webserver to do this. Is that what you are looking for or should opening the `audit-report.html` from the file system? 

I definitely do like the idea of adding that option as a convenience 😄

**Comment by nikolay-borzov** [comment]
Right, just opening `audit-report.html` using the default browser. It seems like natural action when generating report on a local machine

**Comment by nikolay-borzov** [comment]
Would be great if you add `--open` flag description to the README
